package hcc.parse.base

class ParseConstants {
    companion object {
        val IF_STATEMENT_COMMANDS = listOf(
            "biome",
            "block",
            "blocks",
            "data",
            "dimension",
            "entity",
            "loaded",
            "predicate",
            "score"
        )

        val IF_STATEMENT_OPERATORS = listOf(
            "==",
            "<",
            ">",
            "<=",
            "=>"
        )

        val MC_COMMANDS = listOf(
        "advancement",
        "attribute",
        "bossbar",
        "clear",
        "clone",
        "data",
        "damage",
        "datapack",
        "debug",
        "defaultgamemode",
        "difficulty",
        "effect",
        "enchant",
        "execute",
        "experience",
        "fill",
        "fillbiome",
        "forceload",
        "function",
        "gamemode",
        "gamerule",
        "give",
        "help",
        "item",
        "jfr",
        "kick",
        "kill",
        "list",
        "locate",
        "loot",
        "me",
        "msg",
        "particle",
        "place",
        "playsound",
        "publish",
        "recipe",
        "reload",
//        "return",
        "ride",
        "say",
        "schedule",
        "scoreboard",
        "seed",
        "setblock",
        "setworldspawn",
        "spawnpoint",
        "spectate",
        "spreadplayers",
        "stopsound",
        "summon",
        "tag",
        "team",
        "teammsg",
        "teleport",
        "tell",
        "tellraw",
        "time",
        "title",
        "tm",
        "tp",
        "trigger",
        "w",
        "weather",
        "worldborder",
        "xp"
        )
    }
}